### ISSUE TITLE
Conversion between different mergertree formats?

### ISSUE THREAD

**Issue by manodeep** [ytree-project/ytree#111]
(This is a feature request/feasibility check)

There are a couple of tasks that come up frequently enough and I am curious whether `ytree` can be extended to cover those use-cases:

- Given a merger tree file, generate a random subsample of the trees and output in the same file format
- Convert between different mergertree file formats

I know there can be lots of subtle differences between tree formats, but perhaps `ytree` can handle those differences.

**Comment by brittonsmith** [comment]
It's likely possible to do this, but would be an absolutely enormous effort. It's not something I can see myself doing. I'm going to assign this to you.

**Comment by manodeep** [comment]
Hahahahahahahahahaha! Yup - this is totally something I can do. 

Well, then this feature will have to wait for other interested folks :)

**Comment by manodeep** [comment]
(Please feel free to close this - no point keeping issues around that are not in the development plans)

**Comment by brittonsmith** [comment]
Yeah, good idea. I'll close it and put a back burner label on it to find it later.
