### ISSUE TITLE
implicit assumptions for filename for AHF more

### ISSUE THREAD

**Issue by TobiBu** [ytree-project/ytree#116]
### Bug report

**The tree package makes implicit assumptions for the structure of the filename when using AHF**

In the file arbor.py in line 74 when getting the file prefix, cutting the filename at the underscore "_" makes implicit assumptions about the naming convention of the simulation. Similarly in line 83 when getting all the files stored in my_files, the glob command seeks for files with an underscore between prefix and suffix.

I am currently unsure how to solve this, but the most flexible option might be to enable to pass the prefix to the loading function.
For the latter problem replacing the current line 83 with 
`my_files = glob.glob("%s*%s" % (self._prefix, self._suffix))`
solves the issue for me.

**Comment by brittonsmith** [comment]
Hi, thanks for filing this issue. Can you provide some sample data that breaks this assumption? Minimally, it would be useful to see an example of filenames that break the assumption.

**Comment by TobiBu** [comment]
Hi,
thanks a lot for the quick answer and sorry for not providing the minimal example.
I have put some data [here](https://datashare.mpcdf.mpg.de/s/mHYdQTawPqAHSMx) which breaks the code.
Hope that is sufficient.

**Comment by brittonsmith** [comment]
Thanks for this. I've been busy with teaching but am now slowly getting back to things. I'll have a look at this ASAP.

**Comment by brittonsmith** [comment]
Hi @TobiBu, PR #118 should be a general fix for this. Can you give it a try?
