### ISSUE TITLE
inferred redshift at load can become negative

### ISSUE THREAD

**Issue by TobiBu** [ytree-project/ytree#147]
Hi,

when loading a merger tree I just discovered that in some weird cases the redshift can be negativ.
E.g. I have a simulation where z=0 is in fact z=-1e-14 in the AHF catalogue.
This leads to issues when loading the merger tree, as the name is inferred from the redshift value.
A simple fix could be to use np.abs() in the io routine.

**Comment by brittonsmith** [comment]
Hi, thanks for posting this issue. Can you provide some more information on the issue this causes? I don't think taking an absolute value will work in all cases. Negative redshifts are a valid use case up to but not including z = -1. I have worked with some merger trees that do this. In any case, I'm happy to work with you to get this issue fixed.

**Comment by brittonsmith** [comment]
@TobiBu, PR #149 contains a potential fix for this. Can you give it a try and see if it works for you? I've got some data here that also suffers from this issue and it seems to fix it.

**Comment by brittonsmith** [comment]
@TobiBu, I think PR #149 fixes this, so I'm going to close this issue. Please feel free to update if it doesn't or you run into other problems. Thanks again for reporting this.
