### ISSUE TITLE
better error handling when providing the wrong file for TreeFrog frontend

### ISSUE THREAD

**Issue by brittonsmith** [ytree-project/ytree#98]
From the discussion in PR #95,
@manodeep asks:

> If the user provides the forestid file (rather than the foreststats file), then ytree throws an error - “OSError: Could not determine arbor type for VELOCIraptor.tree.t4.0-131.walkabletree.sage.forestID.hdf5.0.”

**Comment by brittonsmith** [comment]
I'll see what I can do about this. It's tricky because we support many different formats using HDF5 data. It takes being able to distinguish a file is of a specific format while not the correct file for that format.

**Comment by manodeep** [comment]
This behaviour would certainly have to sit within the specific `_is_valid` method for the treefrog format handler. Would a set of try-excepts for the known fields (in the `foreststats` and the raw data file) work?

**Comment by brittonsmith** [comment]
Resolved in PR #103.
